# Generated by Django 4.2.5 on 2023-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bakery_products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Bakery_name', models.CharField(max_length=100)),
                ('Portion_size_per_100g', models.CharField(max_length=100)),
                ('Calories', models.CharField(max_length=100)),
                ('Nutritional_content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bakery_products',
            },
        ),
        migrations.CreateModel(
            name='dry_fruits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dryfruit_name', models.CharField(max_length=100)),
                ('Portion_size_per_100g', models.CharField(max_length=100)),
                ('Calories', models.CharField(max_length=100)),
                ('Nutritional_content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dry_fruits',
            },
        ),
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fruits_name', models.CharField(max_length=100)),
                ('Portion_size_per_100g', models.CharField(max_length=100)),
                ('Calories', models.CharField(max_length=100)),
                ('Nutritional_content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fruits',
            },
        ),
        migrations.CreateModel(
            name='meat_eggs_fishes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nonveg_name', models.CharField(max_length=100)),
                ('Portion_size_per_100g', models.CharField(max_length=100)),
                ('Calories', models.CharField(max_length=100)),
                ('Nutritional_content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'meat_eggs_fishes',
            },
        ),
        migrations.CreateModel(
            name='vegetables',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Vegetable_name', models.CharField(max_length=100)),
                ('Portion_size_per_100g', models.CharField(max_length=100)),
                ('Calories', models.CharField(max_length=100)),
                ('Nutritional_content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vegetables',
            },
        ),
    ]
