# Generated by Django 4.2.5 on 2023-10-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_products',
            name='Nutritional_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dry_fruits',
            name='Nutritional_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='Nutritional_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meat_eggs_fishes',
            name='Nutritional_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='Nutritional_content',
            field=models.CharField(max_length=200),
        ),
    ]
