# Generated by Django 4.2.5 on 2023-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_alter_bakery_products_nutritional_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='milk_products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('milkproducts_name', models.CharField(max_length=100)),
                ('Portion_size_per_100g', models.CharField(max_length=100)),
                ('Calories', models.CharField(max_length=100)),
                ('Nutritional_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'milk_products',
            },
        ),
    ]
