# Generated by Django 4.1.2 on 2023-10-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_rename_nonveg_name_meat_eggs_fishes_meat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_products',
            name='Calories',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dry_fruits',
            name='Calories',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='Calories',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meat_eggs_fishes',
            name='Calories',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='milk_products',
            name='Calories',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='Calories',
            field=models.IntegerField(max_length=100),
        ),
    ]
