# Generated by Django 4.2.6 on 2023-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_alter_bakery_products_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_products',
            name='Calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dry_fruits',
            name='Calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='Calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meat_eggs_fishes',
            name='Calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='milk_products',
            name='Calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='Calories',
            field=models.IntegerField(),
        ),
    ]
